### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johnlundberg** [bkpifc/BKPMediaDetector#1]
Hi, this looks very interesting, and I would like to make a Griffeye plugin based on this.
Under what license is the code and model released?

**Comment by bkpifc** [comment]
Hi there. Added the license (Apache 2.0) since all input contribution (namely the Tensorflow framework, the Open Images pre-trained model as well as the AVA pre-trained model) are under this license as well. My own contributions and model (Script, IS Logo Detector) to it therefore as well. Not entirely sure whether all required Python modules as well, though - this would need cross-checking. Let me know if I can be of any further assistance. Would love to see the outcome.

**Comment by johnlundberg** [comment]
Thanks! I'll let you know when I have something to show!
